export { Logo } from './Logo';
export { LeftArrow } from './LeftArrow';
export { RightArrow } from './RightArrow';
export { Arrow } from './Arrow';
export { EvoVideoIcon } from './EvoVideoIcon';
export { Facebook } from './Facebook';
export { Insta } from './Insta';
export { Youtube } from './Youtube';
export { FooterLogo } from './FooterLogo';
